//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Basketball_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int gameID { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan time { get; set; }
        public string venue { get; set; }
        public Nullable<decimal> fee { get; set; }
        public string paid { get; set; }
    }
}
